services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  wordpress:
    image: wordpress:php8.2-fpm
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', '${WP_URL}');
        define('WP_SITEURL', '${WP_URL}');
        define('WP_MEMORY_LIMIT', '${WP_MEMORY_LIMIT}');
        define('WPLANG', '${WP_LOCALE}');
        define('WP_DEBUG', false);
        define('DISALLOW_FILE_EDIT', true);
        define('AUTOMATIC_UPDATER_DISABLED', true);
    volumes:
      - ./wordpress:/var/www/html
      - wp_uploads:/var/www/html/wp-content/uploads
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wordpress:/var/www/html:ro
      - wp_uploads:/var/www/html/wp-content/uploads:ro
    restart: unless-stopped

  wpcli:
    image: wordpress:cli
    depends_on:
      - wordpress
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    working_dir: /var/www/html
    volumes:
      - ./wordpress:/var/www/html
      - wp_uploads:/var/www/html/wp-content/uploads
      - ./init.sh:/init.sh:ro
      - ./docker/php/php-overrides.ini:/usr/local/etc/php/conf.d/zzz-overrides.ini:ro
    entrypoint: ["sh", "-lc"]
    command: "bash"
    restart: "no"

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
    ports:
      - "8085:80"
    restart: unless-stopped

volumes:
  db_data:
  wp_uploads: